package Utils;

import org.apache.log4j.*;

public class Log {
    public  static  Logger log = Logger.getLogger(Log.class.getName());

    // If I want to print ant message in between, I should print the logs

    // When the test starts, I should print the logs

    public static void startTestCase(String testCaseName){
        log.info("********************************************");
        log.info("********************************************");
        log.info("***********"+ testCaseName + "**************");
    }

    // When my tests stops, I should print the logs

    public static void endTestCase(String testCaseName){
        log.info("########################################");
        log.info("########################################");
        log.info("##############"+ testCaseName +"##########################");
    }

    public static void info(String message){
        log.info(message);
    }

    public static void warning(String warning){
        log.info(warning);
    }

    //========================MAVEN LIFECYCLE======================

    //MAVEN LIFE CYCLE: This consists of several phases:
    //Clean: Removes all the files generated by the previous build
    //Validate: it checks the project is correct and all the necessary information is available
    //Compile: compiles the source code of the project
    //Test: runs the tests for the project
    //Package: packages the compiled code into a distributable format, such as JAR or WAR files
    //Verify: runs and checks on results of integration tests to ensure quality criteria is met
    //Install: installs the packages into local repository
    //Site: generates documentation for the project (mostly for developers)
    //Deploy: copies the final package to remote repository for sharing with other developers or projects
}
